"""Add description field to folders

Revision ID: 01bec7ba3aa3
Revises: c8003d5b5f2f
Create Date: 2025-09-26 19:46:42.232147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01bec7ba3aa3'
down_revision: Union[str, None] = 'c8003d5b5f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Migrate existing folder nodes to the new table
    op.execute("""
        INSERT INTO node_folders (id, description)
        SELECT id, NULL
        FROM nodes
        WHERE node_type = 'folder'
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_folders')
    # ### end Alembic commands ###

