"""Initial migration - complete GTD schema

Revision ID: f1683c4cabf0
Revises: 
Create Date: 2025-08-30 07:37:00.205328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1683c4cabf0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'color',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=7),
               existing_nullable=True)
    op.drop_column('tags', 'sort_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('tags', 'color',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###

